openapi: 3.0.1
info:
  title: campaign
  description: API Definition of campaign
  version: 1.0.0
servers:
- url: http://localhost:8290/campaign
paths:
  /:
    get:
      responses:
        default:
          description: Default response
